export default {
  general: {
    cancel: "Cancel",
    close: "Close",
    confirm: "Confirm",
    copy: "Copy",
  },
  buttons: {
    save: "Save",
  },
  njobdesk: {
    label: "NJobDesk",
    tabOverview: "Overview",
    tabJobs: "Jobs",
    tabHistory: "History",
    notConfigured:
      "No scheduler providers are registered. Install a provider package (Quartz, Hangfire, Umbraco) and register it with AddProvider() after AddNJobDesk() in Program.cs.",
    statScheduler: "Scheduler",
    statClustered: "Clustered",
    statJobs: "Jobs",
    statRunning: "Running now",
    statPaused: "Paused",
    statSucceeded24h: "Succeeded (24h)",
    statFailures: "Failed (24h)",
    trendHeadline: "Last 24 hours",
    trendLabel: "Executions per hour over the last 24 hours",
    trendEmpty: "No executions in the last 24 hours.",
    trendSucceeded: "succeeded",
    trendFailed: "failed",
    live: "Live",
    refresh: "Refresh",
    notConfiguredHeadline: "No scheduler providers",
    providerDegraded: "%0% is unavailable.",
    providerUnavailable: "Unavailable",
    colProvider: "Provider",
    metaSchedulerName: "Scheduler name",
    metaInstanceId: "Instance id",
    metaStoreType: "Job store",
    metaThreadPool: "Thread pool size",
    metaRunningSince: "Running since",
    metaProviderVersion: "Provider version",
    metaHistoryEnabled: "Execution history",
    pauseAll: "Pause all",
    resumeAll: "Resume all",
    runningEmpty: "No jobs are running right now.",
    yes: "Yes",
    no: "No",
    enabled: "Enabled",
    disabled: "Disabled",
    filterPlaceholder: "Filter by name or group...",
    showSystemJobs: "Show system jobs",
    jobsEmpty: "No jobs are scheduled.",
    colJob: "Job",
    colSchedule: "Schedule",
    colState: "State",
    colNextFire: "Next fire",
    colLastFire: "Last fire",
    colTriggers: "Triggers",
    colType: "Type",
    colStarted: "Started",
    colFinished: "Finished",
    colDuration: "Duration",
    colError: "Error",
    colNode: "Node",
    colTrigger: "Trigger",
    colCron: "Cron",
    colMisfire: "Misfire policy",
    colElapsed: "Elapsed",
    detailBack: "Back to jobs",
    detailHeadline: "Details",
    detailTimeline: "Run timeline",
    timelineEmpty: "This job has not run yet.",
    filterAll: "All",
    actionMore: "More actions",
    actionPreview: "Next fire times",
    jobsOnboarding: "Jobs from every registered scheduler provider appear here.",
    detailJobType: "Job type",
    detailDescription: "Description",
    detailDurable: "Durable",
    detailConcurrent: "Concurrent execution disallowed",
    detailSystemJob: "System job",
    detailTriggers: "Triggers",
    historyEmpty: "No executions match the current filter.",
    historyAllClear: "All clear — no failures match the current filter.",
    historyFromDate: "From",
    historyToDate: "To",
    loadError: "The NJobDesk API request failed. Check the server log for details.",
    actionTrigger: "Run now",
    actionPause: "Pause",
    actionResume: "Resume",
    actionDelete: "Delete",
    actionUnschedule: "Unschedule",
    actionResetError: "Reset error",
    actionEdit: "Edit schedule",
    editOnlyCron: "Only cron trigger schedules can be edited.",
    confirmDeleteHeadline: "Delete job?",
    confirmDeleteMessage:
      "The job '%0%' and its triggers will be removed from the scheduler. Jobs registered in code are re-created the next time the application restarts.",
    confirmUnscheduleHeadline: "Unschedule trigger?",
    confirmUnscheduleMessage:
      "The trigger '%0%' will be removed and the job will no longer fire on this schedule. Triggers registered in code are re-created the next time the application restarts.",
    confirmPauseAllHeadline: "Pause all triggers?",
    confirmPauseAllMessage: "No jobs will fire on any trigger until the scheduler is resumed.",
    toastTriggered: "Job execution has been queued.",
    toastPaused: "Paused.",
    toastResumed: "Resumed.",
    toastDeleted: "Job deleted.",
    toastUnscheduled: "Trigger unscheduled.",
    toastResetError: "Trigger error state reset.",
    toastRescheduled: "Schedule updated.",
    toastPausedAll: "All triggers paused.",
    toastResumedAll: "All triggers resumed.",
    toastActionFailed: "The action failed. Check the server log for details.",
    modalEditScheduleHeadline: "Edit schedule",
    modalValid: "Valid cron expression",
    modalInvalid: "Invalid cron expression",
    modalNextFires: "Next fire times",
    modalRunLogs: "Logs",
    actionRunDetails: "View run details",
    logsEmpty: "No log entries were captured for this run.",
    logsEmptyHint:
      "Entries logged through ILogger during the run are captured at Information level and above by default. Adjust UmbracoCommunityNJobDesk:History:Logs in configuration to change this.",
    logsNoMatch: "No log entries match the current filter.",
    logsSearchPlaceholder: "Filter log entries...",
    logsCopy: "Copy logs",
    logsPendingRun: "Logs are captured while the job runs and appear here once the run finishes.",
  },
};
