// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { DeleteJobData, DeleteJobErrors, DeleteJobResponses, GetExecutionLogsData, GetExecutionLogsResponses, GetExecutionsData, GetExecutionsResponses, GetJobData, GetJobErrors, GetJobResponses, GetJobsData, GetJobsResponses, GetRunningExecutionsData, GetRunningExecutionsResponses, GetSchedulerStatisticsData, GetSchedulerStatisticsResponses, GetSchedulerStatusData, GetSchedulerStatusResponses, PauseAllData, PauseAllResponses, PauseJobData, PauseJobErrors, PauseJobResponses, PauseTriggerData, PauseTriggerErrors, PauseTriggerResponses, RescheduleTriggerData, RescheduleTriggerErrors, RescheduleTriggerResponses, ResetTriggerErrorData, ResetTriggerErrorErrors, ResetTriggerErrorResponses, ResumeAllData, ResumeAllResponses, ResumeJobData, ResumeJobErrors, ResumeJobResponses, ResumeTriggerData, ResumeTriggerErrors, ResumeTriggerResponses, TriggerJobData, TriggerJobErrors, TriggerJobResponses, UnscheduleTriggerData, UnscheduleTriggerErrors, UnscheduleTriggerResponses, ValidateCronData, ValidateCronResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export class CronService {
    public static validateCron<ThrowOnError extends boolean = false>(options?: Options<ValidateCronData, ThrowOnError>) {
        return (options?.client ?? client).post<ValidateCronResponses, unknown, ThrowOnError>({
            url: '/cron/validate',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
}

export class ExecutionsService {
    public static getExecutions<ThrowOnError extends boolean = false>(options?: Options<GetExecutionsData, ThrowOnError>) {
        return (options?.client ?? client).get<GetExecutionsResponses, unknown, ThrowOnError>({
            url: '/executions',
            ...options
        });
    }
    
    public static getExecutionLogs<ThrowOnError extends boolean = false>(options: Options<GetExecutionLogsData, ThrowOnError>) {
        return (options.client ?? client).get<GetExecutionLogsResponses, unknown, ThrowOnError>({
            url: '/executions/{id}/logs',
            ...options
        });
    }
    
    public static getRunningExecutions<ThrowOnError extends boolean = false>(options?: Options<GetRunningExecutionsData, ThrowOnError>) {
        return (options?.client ?? client).get<GetRunningExecutionsResponses, unknown, ThrowOnError>({
            url: '/executions/running',
            ...options
        });
    }
}

export class JobsService {
    public static getJobs<ThrowOnError extends boolean = false>(options?: Options<GetJobsData, ThrowOnError>) {
        return (options?.client ?? client).get<GetJobsResponses, unknown, ThrowOnError>({
            url: '/jobs',
            ...options
        });
    }
    
    public static deleteJob<ThrowOnError extends boolean = false>(options: Options<DeleteJobData, ThrowOnError>) {
        return (options.client ?? client).delete<DeleteJobResponses, DeleteJobErrors, ThrowOnError>({
            url: '/jobs/{id}',
            ...options
        });
    }
    
    public static getJob<ThrowOnError extends boolean = false>(options: Options<GetJobData, ThrowOnError>) {
        return (options.client ?? client).get<GetJobResponses, GetJobErrors, ThrowOnError>({
            url: '/jobs/{id}',
            ...options
        });
    }
    
    public static triggerJob<ThrowOnError extends boolean = false>(options: Options<TriggerJobData, ThrowOnError>) {
        return (options.client ?? client).post<TriggerJobResponses, TriggerJobErrors, ThrowOnError>({
            url: '/jobs/{id}/trigger',
            ...options
        });
    }
    
    public static pauseJob<ThrowOnError extends boolean = false>(options: Options<PauseJobData, ThrowOnError>) {
        return (options.client ?? client).post<PauseJobResponses, PauseJobErrors, ThrowOnError>({
            url: '/jobs/{id}/pause',
            ...options
        });
    }
    
    public static resumeJob<ThrowOnError extends boolean = false>(options: Options<ResumeJobData, ThrowOnError>) {
        return (options.client ?? client).post<ResumeJobResponses, ResumeJobErrors, ThrowOnError>({
            url: '/jobs/{id}/resume',
            ...options
        });
    }
}

export class SchedulerService {
    public static getSchedulerStatus<ThrowOnError extends boolean = false>(options?: Options<GetSchedulerStatusData, ThrowOnError>) {
        return (options?.client ?? client).get<GetSchedulerStatusResponses, unknown, ThrowOnError>({
            url: '/scheduler',
            ...options
        });
    }
    
    public static getSchedulerStatistics<ThrowOnError extends boolean = false>(options?: Options<GetSchedulerStatisticsData, ThrowOnError>) {
        return (options?.client ?? client).get<GetSchedulerStatisticsResponses, unknown, ThrowOnError>({
            url: '/scheduler/statistics',
            ...options
        });
    }
    
    public static pauseAll<ThrowOnError extends boolean = false>(options?: Options<PauseAllData, ThrowOnError>) {
        return (options?.client ?? client).post<PauseAllResponses, unknown, ThrowOnError>({
            url: '/scheduler/pause-all',
            ...options
        });
    }
    
    public static resumeAll<ThrowOnError extends boolean = false>(options?: Options<ResumeAllData, ThrowOnError>) {
        return (options?.client ?? client).post<ResumeAllResponses, unknown, ThrowOnError>({
            url: '/scheduler/resume-all',
            ...options
        });
    }
}

export class TriggersService {
    public static pauseTrigger<ThrowOnError extends boolean = false>(options: Options<PauseTriggerData, ThrowOnError>) {
        return (options.client ?? client).post<PauseTriggerResponses, PauseTriggerErrors, ThrowOnError>({
            url: '/triggers/{id}/pause',
            ...options
        });
    }
    
    public static resumeTrigger<ThrowOnError extends boolean = false>(options: Options<ResumeTriggerData, ThrowOnError>) {
        return (options.client ?? client).post<ResumeTriggerResponses, ResumeTriggerErrors, ThrowOnError>({
            url: '/triggers/{id}/resume',
            ...options
        });
    }
    
    public static resetTriggerError<ThrowOnError extends boolean = false>(options: Options<ResetTriggerErrorData, ThrowOnError>) {
        return (options.client ?? client).post<ResetTriggerErrorResponses, ResetTriggerErrorErrors, ThrowOnError>({
            url: '/triggers/{id}/reset-error',
            ...options
        });
    }
    
    public static unscheduleTrigger<ThrowOnError extends boolean = false>(options: Options<UnscheduleTriggerData, ThrowOnError>) {
        return (options.client ?? client).delete<UnscheduleTriggerResponses, UnscheduleTriggerErrors, ThrowOnError>({
            url: '/triggers/{id}',
            ...options
        });
    }
    
    public static rescheduleTrigger<ThrowOnError extends boolean = false>(options: Options<RescheduleTriggerData, ThrowOnError>) {
        return (options.client ?? client).put<RescheduleTriggerResponses, RescheduleTriggerErrors, ThrowOnError>({
            url: '/triggers/{id}/schedule',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
}
