// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type CronValidationRequestModel = {
    cronExpression: string;
    nextFireTimeCount: number;
    timeZoneId?: string | null;
};

export type CronValidationResultModel = {
    isValid: boolean;
    error?: string | null;
    summary?: string | null;
    nextFireTimesUtc: Array<string>;
};

export type ExecutionBucketModel = {
    hourStartUtc: string;
    succeeded: number;
    failed: number;
};

export type ExecutionLogLevel = 'Trace' | 'Debug' | 'Information' | 'Warning' | 'Error' | 'Critical';

export type ExecutionLogModel = {
    timestampUtc: string;
    level: ExecutionLogLevel;
    category: string;
    message: string;
    exception?: string | null;
    properties?: string | null;
};

export type ExecutionModel = {
    id: number;
    jobGroup: string;
    jobName: string;
    triggerGroup: string;
    triggerName: string;
    startedUtc: string;
    finishedUtc?: string | null;
    durationMs?: number | null;
    state: ExecutionStatus;
    errorMessage?: string | null;
    schedulerInstanceId: string;
    recovering: boolean;
};

export type ExecutionModelPagedResult = {
    total: number;
    items: Array<ExecutionModel>;
};

export type ExecutionStatus = 'Running' | 'Succeeded' | 'Failed' | 'Vetoed';

export type JobDetailModel = {
    job: JobSummaryModel;
    triggers: Array<TriggerModel>;
    recentExecutions: Array<ExecutionModel>;
};

export type JobState = 'None' | 'Normal' | 'Paused' | 'Blocked' | 'Error' | 'Complete';

export type JobSummaryModel = {
    group: string;
    name: string;
    description?: string | null;
    jobType?: string | null;
    durable: boolean;
    concurrentExecutionDisallowed: boolean;
    triggerCount: number;
    scheduleSummary?: string | null;
    state: JobState;
    nextFireTimeUtc?: string | null;
    previousFireTimeUtc?: string | null;
    isSystemJob: boolean;
};

export type JobSummaryModelPagedResult = {
    total: number;
    items: Array<JobSummaryModel>;
};

export type ProblemDetails = {
    type?: string | null;
    title?: string | null;
    status?: number | null;
    detail?: string | null;
    instance?: string | null;
    [key: string]: unknown | string | null | string | null | number | null | string | null | string | null | undefined;
};

export type RescheduleRequestModel = {
    cronExpression: string;
    timeZoneId?: string | null;
};

export type SchedulerState = 'NotConfigured' | 'Stopped' | 'Started' | 'Standby' | 'Shutdown';

export type SchedulerStatisticsModel = {
    jobsTotal: number;
    jobsPaused: number;
    runningCount: number;
    succeeded24h: number;
    failed24h: number;
    buckets: Array<ExecutionBucketModel>;
};

export type SchedulerStatusModel = {
    state: SchedulerState;
    schedulerName?: string | null;
    schedulerInstanceId?: string | null;
    clustered: boolean;
    schedulerEnabled: boolean;
    historyEnabled: boolean;
    storeType?: string | null;
    threadPoolSize: number;
    runningSinceUtc?: string | null;
    providerVersion?: string | null;
    readOnly: boolean;
};

export type TriggerModel = {
    group: string;
    name: string;
    description?: string | null;
    type: TriggerType;
    cronExpression?: string | null;
    cronSummary?: string | null;
    timeZoneId?: string | null;
    state: JobState;
    nextFireTimeUtc?: string | null;
    previousFireTimeUtc?: string | null;
    startTimeUtc: string;
    endTimeUtc?: string | null;
    misfireInstruction: string;
    priority: number;
};

export type TriggerType = 'Cron' | 'Simple' | 'Other';

export type ValidateCronData = {
    body?: CronValidationRequestModel;
    path?: never;
    query?: never;
    url: '/njobdesk/api/v1/cron/validate';
};

export type ValidateCronResponses = {
    /**
     * OK
     */
    200: CronValidationResultModel;
};

export type ValidateCronResponse = ValidateCronResponses[keyof ValidateCronResponses];

export type GetExecutionsData = {
    body?: never;
    path?: never;
    query?: {
        skip?: number;
        take?: number;
        jobGroup?: string;
        jobName?: string;
        state?: ExecutionStatus;
        fromUtc?: string;
        toUtc?: string;
    };
    url: '/njobdesk/api/v1/executions';
};

export type GetExecutionsResponses = {
    /**
     * OK
     */
    200: ExecutionModelPagedResult;
};

export type GetExecutionsResponse = GetExecutionsResponses[keyof GetExecutionsResponses];

export type GetExecutionLogsData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/njobdesk/api/v1/executions/{id}/logs';
};

export type GetExecutionLogsResponses = {
    /**
     * OK
     */
    200: Array<ExecutionLogModel>;
};

export type GetExecutionLogsResponse = GetExecutionLogsResponses[keyof GetExecutionLogsResponses];

export type GetRunningExecutionsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/njobdesk/api/v1/executions/running';
};

export type GetRunningExecutionsResponses = {
    /**
     * OK
     */
    200: Array<ExecutionModel>;
};

export type GetRunningExecutionsResponse = GetRunningExecutionsResponses[keyof GetRunningExecutionsResponses];

export type GetJobsData = {
    body?: never;
    path?: never;
    query?: {
        skip?: number;
        take?: number;
        group?: string;
        filter?: string;
    };
    url: '/njobdesk/api/v1/jobs';
};

export type GetJobsResponses = {
    /**
     * OK
     */
    200: JobSummaryModelPagedResult;
};

export type GetJobsResponse = GetJobsResponses[keyof GetJobsResponses];

export type DeleteJobData = {
    body?: never;
    path: {
        group: string;
        name: string;
    };
    query?: never;
    url: '/njobdesk/api/v1/jobs/{group}/{name}';
};

export type DeleteJobErrors = {
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type DeleteJobError = DeleteJobErrors[keyof DeleteJobErrors];

export type DeleteJobResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetJobData = {
    body?: never;
    path: {
        group: string;
        name: string;
    };
    query?: never;
    url: '/njobdesk/api/v1/jobs/{group}/{name}';
};

export type GetJobErrors = {
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type GetJobError = GetJobErrors[keyof GetJobErrors];

export type GetJobResponses = {
    /**
     * OK
     */
    200: JobDetailModel;
};

export type GetJobResponse = GetJobResponses[keyof GetJobResponses];

export type TriggerJobData = {
    body?: never;
    path: {
        group: string;
        name: string;
    };
    query?: never;
    url: '/njobdesk/api/v1/jobs/{group}/{name}/trigger';
};

export type TriggerJobErrors = {
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type TriggerJobError = TriggerJobErrors[keyof TriggerJobErrors];

export type TriggerJobResponses = {
    /**
     * OK
     */
    200: JobDetailModel;
};

export type TriggerJobResponse = TriggerJobResponses[keyof TriggerJobResponses];

export type PauseJobData = {
    body?: never;
    path: {
        group: string;
        name: string;
    };
    query?: never;
    url: '/njobdesk/api/v1/jobs/{group}/{name}/pause';
};

export type PauseJobErrors = {
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type PauseJobError = PauseJobErrors[keyof PauseJobErrors];

export type PauseJobResponses = {
    /**
     * OK
     */
    200: JobDetailModel;
};

export type PauseJobResponse = PauseJobResponses[keyof PauseJobResponses];

export type ResumeJobData = {
    body?: never;
    path: {
        group: string;
        name: string;
    };
    query?: never;
    url: '/njobdesk/api/v1/jobs/{group}/{name}/resume';
};

export type ResumeJobErrors = {
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type ResumeJobError = ResumeJobErrors[keyof ResumeJobErrors];

export type ResumeJobResponses = {
    /**
     * OK
     */
    200: JobDetailModel;
};

export type ResumeJobResponse = ResumeJobResponses[keyof ResumeJobResponses];

export type GetSchedulerStatusData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/njobdesk/api/v1/scheduler';
};

export type GetSchedulerStatusResponses = {
    /**
     * OK
     */
    200: SchedulerStatusModel;
};

export type GetSchedulerStatusResponse = GetSchedulerStatusResponses[keyof GetSchedulerStatusResponses];

export type GetSchedulerStatisticsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/njobdesk/api/v1/scheduler/statistics';
};

export type GetSchedulerStatisticsResponses = {
    /**
     * OK
     */
    200: SchedulerStatisticsModel;
};

export type GetSchedulerStatisticsResponse = GetSchedulerStatisticsResponses[keyof GetSchedulerStatisticsResponses];

export type PauseAllData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/njobdesk/api/v1/scheduler/pause-all';
};

export type PauseAllResponses = {
    /**
     * OK
     */
    200: SchedulerStatusModel;
};

export type PauseAllResponse = PauseAllResponses[keyof PauseAllResponses];

export type ResumeAllData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/njobdesk/api/v1/scheduler/resume-all';
};

export type ResumeAllResponses = {
    /**
     * OK
     */
    200: SchedulerStatusModel;
};

export type ResumeAllResponse = ResumeAllResponses[keyof ResumeAllResponses];

export type PauseTriggerData = {
    body?: never;
    path: {
        group: string;
        name: string;
    };
    query?: never;
    url: '/njobdesk/api/v1/triggers/{group}/{name}/pause';
};

export type PauseTriggerErrors = {
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type PauseTriggerError = PauseTriggerErrors[keyof PauseTriggerErrors];

export type PauseTriggerResponses = {
    /**
     * OK
     */
    200: TriggerModel;
};

export type PauseTriggerResponse = PauseTriggerResponses[keyof PauseTriggerResponses];

export type ResumeTriggerData = {
    body?: never;
    path: {
        group: string;
        name: string;
    };
    query?: never;
    url: '/njobdesk/api/v1/triggers/{group}/{name}/resume';
};

export type ResumeTriggerErrors = {
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type ResumeTriggerError = ResumeTriggerErrors[keyof ResumeTriggerErrors];

export type ResumeTriggerResponses = {
    /**
     * OK
     */
    200: TriggerModel;
};

export type ResumeTriggerResponse = ResumeTriggerResponses[keyof ResumeTriggerResponses];

export type ResetTriggerErrorData = {
    body?: never;
    path: {
        group: string;
        name: string;
    };
    query?: never;
    url: '/njobdesk/api/v1/triggers/{group}/{name}/reset-error';
};

export type ResetTriggerErrorErrors = {
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type ResetTriggerErrorError = ResetTriggerErrorErrors[keyof ResetTriggerErrorErrors];

export type ResetTriggerErrorResponses = {
    /**
     * OK
     */
    200: TriggerModel;
};

export type ResetTriggerErrorResponse = ResetTriggerErrorResponses[keyof ResetTriggerErrorResponses];

export type UnscheduleTriggerData = {
    body?: never;
    path: {
        group: string;
        name: string;
    };
    query?: never;
    url: '/njobdesk/api/v1/triggers/{group}/{name}';
};

export type UnscheduleTriggerErrors = {
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type UnscheduleTriggerError = UnscheduleTriggerErrors[keyof UnscheduleTriggerErrors];

export type UnscheduleTriggerResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type RescheduleTriggerData = {
    body?: RescheduleRequestModel;
    path: {
        group: string;
        name: string;
    };
    query?: never;
    url: '/njobdesk/api/v1/triggers/{group}/{name}/schedule';
};

export type RescheduleTriggerErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type RescheduleTriggerError = RescheduleTriggerErrors[keyof RescheduleTriggerErrors];

export type RescheduleTriggerResponses = {
    /**
     * OK
     */
    200: TriggerModel;
};

export type RescheduleTriggerResponse = RescheduleTriggerResponses[keyof RescheduleTriggerResponses];
